### ISSUE TITLE
Stack Dump in "How to create cohorts"

### ISSUE THREAD

**Issue by wlongabaugh** [isb-cgc/Community-Notebooks#13]
Following the "Find Interesting Fields" cell here:
https://nbviewer.jupyter.org/github/isb-cgc/Community-Notebooks/blob/master/Notebooks/How_to_create_cohorts.ipynb
There is a stack trace in the preserved output. Is that meant to be there?

**Comment by lhagen-isb** [comment]
No, it's not meant to be there. I have it updated in my fork and was waiting to push it through with any more updates or new notebooks. I can create a pull request to have it updated.

**Comment by lhagen-isb** [comment]
This has been fixed and is in production.
