### ISSUE TITLE
Need instructions for how to start jupyter in the Google Cloud

### ISSUE THREAD

**Issue by Gibbsdavidl** [isb-cgc/Community-Notebooks#2]
What is the absolute easiest way to get jupyter running on a VM?

**Comment by jcorn427** [comment]
Well, you can run jupyter from a docker container. That might be a pretty simple way to get it running on a vm.

**Comment by wlongabaugh** [comment]
I think the easiest way is through Cloud Datalab:
`gcloud components install datalab`
`datalab create`
