### ISSUE TITLE
I think the unnesting will a bit difficult to understand solely by the code, maybe we can provide a little more info, or links to easily understand why is needed?

### ISSUE THREAD

**Issue by boaguilar** [isb-cgc/Community-Notebooks#46]
https://github.com/isb-cgc/Community-Notebooks/blob/c9733579a25773ecc0e0c5c9b08f4ace8084db20/Notebooks/How_to_perform_complex_joins.ipynb#L381

**Comment by Gibbsdavidl** [comment]
I added this text above the unnesting query.

#### Third Join -- detour
Now to bring in the methylation data.  This data, from Illumina methylation arrays, the Human Methylation 27k and 450k platforms, is indexed by probe IDs. That means we first need to do ane extra join to bring in gene symbols.  Also, observe that the methylation annotation is a nested table. In the table schema, you will notice the UCSC field is a record with three components, RefGene_Name, RefGene_Group, and RefGene_Accession. To make our work easier, we want to take this nested table and make it a 'flat' table. For some documentation on doing that see [this doc](https://cloud.google.com/bigquery/docs/reference/standard-sql/arrays#flattening_arrays).
