### ISSUE TITLE
Stale URL in How_to_make_a_heatmap_using_BigQuery.ipynb

### ISSUE THREAD

**Issue by edeutsch** [isb-cgc/Community-Notebooks#52]
In How_to_make_a_heatmap_using_BigQuery.ipynb

The URL http://software.broadinstitute.org/gsea/msigdb/download_geneset.jsp?geneSetName=HALLMARK_TGF_BETA_SIGNALING&fileType=txt gives me a HTTP 302 error.

I think https://www.gsea-msigdb.org/gsea/msigdb/download_geneset.jsp?geneSetName=HALLMARK_TGF_BETA_SIGNALING&fileType=txt is now the correct one?

**Comment by lhagen-isb** [comment]
I believe you are correct that the second one is now the URL to use. I'm currently working on updating the notebook. Thanks for letting us know!

**Comment by edeutsch** [comment]
thanks! I should have and meant to mention that using the first URL I get:
```
'<title>302 Found</title>','</head><body>','<h1>Found</h1>','<p>The document has moved <a href="https://www.gsea-msigdb.org/gsea/msigdb/download_geneset.jsp?geneSetName=HALLMARK_TGF_BETA_SIGNALING">here</a>.</p>','</body></html>' 
```

**Comment by lhagen-isb** [comment]
Thanks! I updated the link URL in the notebook. Please let us know if you run into any more issues.
